### ISSUE TITLE
Y520 issue with USB and Bluetooth (DW1560)

### ISSUE THREAD

**Issue by ImmersiveX** [the-braveknight/Lenovo-Y520-macOS#10]
Because there is no custom SSDT mapping USB ports properly, issues arise when waking up the device causing Bluetooth (DW1560) to stop working until restart.
I think mapping USB ports properly is a good idea, but I am unsure how one would automate the process.
Please advise

**Comment by the-braveknight** [comment]
USB port mapping using USBInjectAll.kext + SSDT-UIAC is not required since the native DSDT has correct _UPC port configuration. If you have any problem, use the forums and provide "Problem Reporting" files.
