### ISSUE TITLE
Nvidia Optimus support with latest Pascal drivers?

### ISSUE THREAD

**Issue by AdiDotJagi** [the-braveknight/Lenovo-Y520-macOS#11]
Hi!

I am planning to switch on my Legion Y520 i7 16GB GTX1060 Max-Q from Windows 10 to macOS Mojave + Windows 10 on Parallels because i heard that Nvidia Optimus is partly working on "new" nvidia pascal drivers (high powered card all the time, igpu disabled) ( https://www.tonymacx86.com/threads/nvidia-gtx-1060-optimus-card-working-in-sierra-on-latest-pascal-drivers.221891/ ). Is that true? Can we use our high power graphics card with hackintosh on our laptops? Does anybody configured this on Legion Y520?

Thanx in advance

(sorry if this is wrong place to post this)

**Comment by ImmersiveX** [comment]
Read the whole post.
Nvidia Optimus will most likely never be supported.
